trigger:
  - main

variables:
  - group: TerraformBackendConfig  # Backend config stored in variable group

pool:
  vmImage: 'ubuntu-latest'

stages:

  # Stage 1: Terraform Init
  - stage: TerraformInit
    displayName: 'Terraform Init Stage'
    jobs:
      - job: Init
        displayName: 'Terraform Init Job'
        steps:
          - checkout: self
          
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init (Install Modules)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainer)'
              backendAzureRmKey: '$(backendStateFile)'

          - publish: $(System.DefaultWorkingDirectory)/.terraform
            artifact: terraform-modules
            displayName: 'Publish Terraform Modules'

  # Stage 2: Terraform Validate & Plan
  - stage: TerraformValidateAndPlan
    displayName: 'Terraform Validate & Plan Stage'
    dependsOn: TerraformInit
    jobs:
      - job: ValidateAndPlan
        displayName: 'Terraform Validate & Plan Job'
        steps:
          - checkout: self

          - download: current
            artifact: terraform-modules
            displayName: 'Download Terraform Modules Artifact'

          - script: |
              cp -r $(Pipeline.Workspace)/terraform-modules $(System.DefaultWorkingDirectory)/.terraform
            displayName: 'Restore Terraform Modules'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: '-var-file=terraform.tfvars -out=tfplan.binary'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - publish: $(System.DefaultWorkingDirectory)
            artifact: terraform-plan-$(Build.BuildId)
            displayName: 'Publish Terraform Plan Artifact'

  # Stage 3: Terraform Apply (Manual approval can be added later)
  - stage: TerraformApply
    displayName: 'Terraform Apply Stage'
    dependsOn: TerraformValidateAndPlan
    jobs:
      - deployment: Apply
        displayName: 'Terraform Apply Deployment'
        environment: 'dev'  # Define this in Azure DevOps Environments
        strategy:
          runOnce:
            deploy:
              steps:
                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: 'latest'

                # Optional: Add approval step before apply
                # - task: ManualValidation@0
                #   inputs:
                #     notifyUsers: '["youruser@example.com"]'
                #     instructions: 'Review plan and approve to apply'
                #     timeoutInMinutes: 1440

                - download: current
                  artifact: terraform-plan-$(Build.BuildId)
                  displayName: 'Download Terraform Plan Artifact'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(Pipeline.Workspace)/terraform-plan-$(Build.BuildId)'
                    commandOptions: 'tfplan.binary'
                    environmentServiceNameAzureRM: '$(serviceConnection)'
