trigger:
  - main

variables:
  - group: TerraformBackendConfig  # Your backend variables group

pool:
  vmImage: 'ubuntu-latest'

stages:
  # Stage 1: Terraform Init
  - stage: TerraformInit
    displayName: 'Terraform Init'
    jobs:
      - job: Init
        displayName: 'Terraform Init Job'
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainer)'
              backendAzureRmKey: '$(backendStateFile)'

  # Stage 2: Terraform Validate & Plan
  - stage: TerraformValidateAndPlan
    displayName: 'Terraform Validate & Plan'
    dependsOn: TerraformInit
    jobs:
      - job: ValidateAndPlan
        displayName: 'Terraform Validate & Plan Job'
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: '-var-file=terraform.tfvars -out=tfplan.binary'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Terraform Plan Artifact'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifact: 'artifact-$(Build.BuildId)'

  # Stage 3: Terraform Apply with Manual Approval
  - stage: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformValidateAndPlan
    jobs:
      - deployment: Apply
        displayName: 'Terraform Apply Deployment'
        environment: 'dev'  # Define this environment in Azure DevOps UI
        strategy:
          runOnce:
            deploy:
              steps:
                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: 'latest'

                - download: current
                  artifact: artifact-$(Build.BuildId)
                  displayName: 'Download Terraform Plan Artifact'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(Pipeline.Workspace)/artifact-$(Build.BuildId)'
                    commandOptions: 'tfplan.binary'
                    environmentServiceNameAzureRM: '$(serviceConnection)'
