trigger:
  batch: true
  branches:
    include:
    - main
    - dev

pool:
  name: 'Default'

parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'dev'
  values:
  - dev
  - staging
  - prod

- name: tfAction
  displayName: 'Terraform Action'
  type: string
  default: 'validate & plan'
  values:
  - validate & plan
  - plan & apply
  - apply
  - destroy

stages:
- stage: Terraform
  displayName: "Terraform - ${{ parameters.tfAction }} - ${{ parameters.environment }}"
  condition: always()
  jobs:
  - template: Pipeline/common/templates/terraform.yml
    parameters:
      environment: ${{ parameters.environment }}
      tfAction: ${{ parameters.tfAction }}
  # # Manual approval for apply or destroy in staging/prod environments
  # - ${{ if and(
  #       or(eq(parameters.tfAction, 'apply'), eq(parameters.tfAction, 'destroy'), eq(parameters.tfAction, 'plan & apply')),
  #       or(eq(parameters.environment, 'staging'), eq(parameters.environment, 'prod'))
  #     ) }}:
  #     - approval:
  #         name: Manual Approval for ${{ parameters.tfAction }} in ${{ parameters.environment }}
  #         timeout: 1.00:00:00
  #         instructions: 'Please approve or reject the deployment for ${{ parameters.environment }}'
