trigger:
  - main

variables:
  - group: TerraformBackendConfig  # Variable group containing serviceConnection, backendResourceGroup, etc.

pool:
  vmImage: 'ubuntu-latest'

stages:
  # Stage 1: Terraform Init (Module + Provider Setup)
  - stage: TerraformInit
    displayName: 'Terraform Init Stage'
    jobs:
      - job: Init
        displayName: 'Terraform Init Job'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainer)'
              backendAzureRmKey: '$(backendStateFile)'

  # Stage 2: Terraform Validate & Plan
  - stage: TerraformValidateAndPlan
    displayName: 'Terraform Validate & Plan Stage'
    dependsOn: TerraformInit
    jobs:
      - job: ValidateAndPlan
        displayName: 'Terraform Validate & Plan Job'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: '-var-file=terraform.tfvars -out=tfplan.binary'
              environmentServiceNameAzureRM: '$(serviceConnection)'

          - publish: $(System.DefaultWorkingDirectory)
            artifact: terraform-plan-$(Build.BuildId)
            displayName: 'Publish Terraform Plan Artifact'

  # Stage 3: Terraform Apply (with Init for provider permissions)
  - stage: TerraformApply
    displayName: 'Terraform Apply Stage'
    dependsOn: TerraformValidateAndPlan
    jobs:
      - deployment: Apply
        displayName: 'Terraform Apply Deployment'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: 'latest'

                - download: current
                  artifact: terraform-plan-$(Build.BuildId)
                  displayName: 'Download Terraform Plan Artifact'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Init (Reinitialize for Apply)'
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/'
                    environmentServiceNameAzureRM: '$(serviceConnection)'
                    backendServiceArm: '$(serviceConnection)'
                    backendAzureRmResourceGroupName: '$(backendResourceGroup)'
                    backendAzureRmStorageAccountName: '$(backendStorageAccount)'
                    backendAzureRmContainerName: '$(backendContainer)'
                    backendAzureRmKey: '$(backendStateFile)'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/'
                    commandOptions: 'tfplan.binary'
                    environmentServiceNameAzureRM: '$(serviceConnection)'
