trigger:
  batch: true
  branches:
    include:
    - main
    - dev

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'dev'
  values:
  - dev
  - staging
  - prod

- name: tfAction
  displayName: 'Terraform Action'
  type: string
  default: 'validate & plan'
  values:
  - validate & plan
  - plan & apply
  - apply
  - destroy

stages:
- stage: Terraform
  displayName: "Terraform - ${{ parameters.tfAction }} - ${{ parameters.environment }}"
  condition: always()
  jobs:
  - template: pipeline/common/templates/terraform.yml
    parameters:
      environment: ${{ parameters.environment }}
      tfAction: ${{ parameters.tfAction }}
  # Manual approvals for apply or destroy in staging/prod
  # ${{ if and(
  #       or(eq(parameters.tfAction, 'apply'), eq(parameters.tfAction, 'destroy'), eq(parameters.tfAction, 'plan & apply')),
  #       or(eq(parameters.environment, 'staging'), eq(parameters.environment, 'prod'))
  #     ) }}:
  #   environment:
  #     name: ${{ parameters.environment }}
