trigger: none

parameters:
  - name: environment
    default: dev
  - name: tfAction
    default: plan

stages:
- stage: Terraform_${{ parameters.environment }}
  displayName: "Terraform Stage - ${{ parameters.environment }}"
  jobs:
    - template: common/templates/pipeline.yml
      parameters:
        environment: ${{ parameters.environment }}
        tfAction: ${{ parameters.tfAction }}
